<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>arm_perception</name>
  <version>0.2.0</version>
  <description>YOLO RGB-D and RGB planar pose estimation with autonomous pick integration.</description>
  <maintainer email="inceer22@gmail.com">Emre Inceer</maintainer>
  <license>Proprietary</license>


  <depend>rclpy</depend>
  <depend>sensor_msgs</depend>
  <depend>sensor_msgs_py</depend>
  <depend>geometry_msgs</depend>
  <depend>visualization_msgs</depend>
  <depend>vision_msgs</depend>
  <exec_depend>rosbag2</exec_depend>
  <depend>std_msgs</depend>
  <depend>cv_bridge</depend>
  <depend>tf2_ros</depend>
  <depend>arm_interfaces</depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>arm_gazebo</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>python3-opencv</exec_depend>
  <exec_depend>python3-yaml</exec_depend>

  <test_depend>ament_pep257</test_depend>
  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
