// Generated by tools/generate_robot_config.py; do not edit manually.
// Source: src/robot_arm_description/config/servo_calibration.yaml
#pragma once

namespace robot_arm {

constexpr char kCalibrationSha256[] = "caf4354aa8ae6801c2305c3f164f6e99fbb2df6ce1e004edf19f5684111f48bb";
constexpr char kCalibrationSha256Short[] = "caf4354aa8ae";
// Answered verbatim to the host's 'K?' request. arm_hardware derives
// the same value from the same YAML at load time and refuses to
// activate when the two disagree, so a YAML edited without reflashing
// cannot silently drive against limits this firmware is not enforcing.
constexpr char kCalibrationFingerprint[] = "21aecfe95643057d";

constexpr ServoCalibration kServoConfig[kServoCount] = {
  {13U, 0U, -89.954374f, 89.954374f, -87.089585f, 87.089585f, 0.000000f, 500U, 2500U, 22.918312f, 15.000000f, 0.750000f, false},
  {14U, 1U, -89.954374f, 89.954374f, -124.331842f, 49.847328f, 37.242257f, 500U, 2500U, 22.918312f, 12.000000f, 0.750000f, false},
  {25U, 2U, -89.954374f, 89.954374f, -158.153540f, 16.025630f, 71.063955f, 500U, 2500U, 22.918312f, 12.000000f, 0.750000f, false},
  {26U, 3U, -89.954374f, 89.954374f, -75.630429f, 98.548741f, -11.459156f, 500U, 2500U, 22.918312f, 20.000000f, 1.250000f, false},
  {27U, 4U, -89.954374f, 89.954374f, -81.360007f, 55.003948f, -5.729578f, 500U, 2500U, 22.918312f, 20.000000f, 1.250000f, false},
  {33U, 5U, -14.323945f, 20.053523f, -17.183004f, 17.194463f, 2.859059f, 500U, 2500U, 22.918312f, 15.000000f, 1.250000f, false},
};

}  // namespace robot_arm
