<?xml version="1.0"?>
<package format="3">
  <name>arm_ml</name>
  <version>0.1.0</version>
  <description>Deep Learning-based Inverse Kinematics for 6DOF Robotic Arm</description>
  <maintainer email="inceer22@gmail.com">Emre Inceer</maintainer>
  <license>Proprietary</license>

  <depend>rclpy</depend>
  <depend>geometry_msgs</depend>
  <depend>arm_interfaces</depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
